# Generated by Django 4.2.2 on 2023-06-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity_reconciliation', '0002_alter_user_createdat_alter_user_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deletedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity_reconciliation.user'),
        ),
    ]
